version: '2.2'
services:
  mysql:
    image: mysql:5.6.36
    container_name: notitas_louquitas
    cpu_percent: 1
    cpus: 0.3
    mem_limit: 1300m
    mem_reservation: 1024m
    ports:
      - 3306:3306
    volumes:
      - my-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
volumes:
  my-data: